# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'orange_fruits_ios_programming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for orange_fruits_ios_programming
  pod 'Iconic', :git => 'https://github.com/zvving/Iconic.git', :branch => 'pod_config'

end
